[package]
name = "cargo-quick-new"
version = "0.1.1"
authors = ["TheAIguy_"]
edition = "2021"
description = "A cargo subcommand for quickly creating a new project."
repository = "https://github.com/TheAIguy-dev/cargo-quick-new"
license = "MIT"

[dependencies]
